### ISSUE TITLE
is there any instructions to upload this file to the router?

### ISSUE THREAD

**Issue by vedmalex** [rusnazip/totolink-padavan#1]
I've got this router and find out that there is a firmware 
can you point me to process of update

**Comment by rusnazip** [comment]
Hi
Build instructions are on [4pda.to](https://4pda.to/forum/index.php?s=&showtopic=961559&view=findpost&p=96732063)
The configuration was created a long time ago and there may be problems when building new versions. Upload firmware in recovery mode

**Comment by vedmalex** [comment]
Thank you for such a quick response

**Comment by vedmalex** [comment]
I've updates the firmware! cool! once more thank you!

using this instruction

Прошивка от NAZIP = [Padavan](https://4pda.to/forum/dl/post/19951915/A7000R-5.0_3.4.3.9-099.trx.zip)
Инструкция - как в теме с бета прошивкой только указываете файл прошивки от Padavan
Инструкция:
подготавливаем ПК
1. В настройках сетевой карты ПК выставить статические параметры ip
ip-adress - 192.168.1.10
маска 255.255.255.0
остальные параметры по нулям
2. Подключаем ПК и роутер кабелем из комплекта. В роутер в порт LAN1
3. Выключаем роутер - зажимаем кнопку на корпусе RST и удерживая ее подаем питание на роутер. Продолжаем держать кнопку RST 20сек.
4. В WEB браузере в адресной строке вводим 192.168.1.1
в появившемся окне выбираем где храниться прошивка от Padavan и нажимаем Upgrade Firmware.


Ждем завершения обновления и после чего в настройках сетевой карты возвращаем настройки получения ip адреc и DNS автоматически.
после завершения процесса обновления, панель управления доступна по адресу 192.168.2.1
базовый логин от панели : admin
базовый пароль от панели : admin
WIFI пароль - 1234567890

**Comment by rusnazip** [comment]
Good luck using it
